/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Autotective.UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Charlotte
 */
public class MainUI extends javax.swing.JFrame {
    TesterUI testerWindow;
    EngineerUI engineerWindow;
    String testerNAME;
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
    static final String DB_URL = "jdbc:mysql://localhost:3306/autotective";
    //Database credentials
    static final String USER = "root";
    static final String PASS = "testpass";
    
    JComboBox jc = new JComboBox();
    JPanel panel = new JPanel();
    Connection con;
    Statement st;
    ResultSet rs;
    
    
    

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        autotectiveLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        engineerButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setTitle("Autotective");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 204, 0));
        jPanel1.setToolTipText("");
        jPanel1.setFont(new java.awt.Font("Heiti SC", 0, 13)); // NOI18N

        autotectiveLabel.setFont(new java.awt.Font("Heiti SC", 0, 48)); // NOI18N
        autotectiveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autotectiveLabel.setText("Autotective");
        autotectiveLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        autotectiveLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        loginButton.setFont(new java.awt.Font("Heiti TC", 1, 24)); // NOI18N
        loginButton.setForeground(new java.awt.Color(0, 153, 102));
        loginButton.setText("Login");
        loginButton.setMaximumSize(new java.awt.Dimension(95, 40));
        loginButton.setMinimumSize(new java.awt.Dimension(95, 40));
        loginButton.setPreferredSize(new java.awt.Dimension(95, 40));
        loginButton.setSize(new java.awt.Dimension(97, 40));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        usernameField.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        usernameField.setForeground(new java.awt.Color(0, 153, 102));
        usernameField.setPreferredSize(new java.awt.Dimension(200, 40));

        jLabel2.setFont(new java.awt.Font("Heiti SC", 0, 24)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Heiti SC", 0, 24)); // NOI18N
        jLabel3.setText("Password");

        passwordField.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N

        engineerButton.setFont(new java.awt.Font("Heiti SC", 0, 14)); // NOI18N
        engineerButton.setText("Engineer Login");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Autotective/UI/images.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(engineerButton)
                        .addGap(70, 70, 70)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(autotectiveLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addComponent(autotectiveLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(engineerButton)
                    .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(194, 194, 194))
        );

        autotectiveLabel.getAccessibleContext().setAccessibleName("jLabel1");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        String username = usernameField.getText();
        String password = passwordField.getText();
        boolean userFlag = false;
        
        //hardcoded "user" and "pass" ... always works
        if( (username.contentEquals("user")) && password.contentEquals("pass")){
            userFlag = true;
            if(testerWindow == null) {
                testerWindow = new TesterUI();
            } 
//            testerNAME = username;
//            testerWindow.autotectiveLabel2.setText(username);
            testerWindow.setVisible(true);
            testerWindow.backWindow=this;
            this.setVisible(false); 

        //hardcoded "engineer" and "pass" ... always works    
        } else if( (username.contentEquals("engineer")) && password.contentEquals("pass")
                && engineerButton.isSelected() ){
            userFlag = true;
          if(engineerWindow == null) {
                engineerWindow = new EngineerUI();
          }      
            engineerWindow.setVisible(true);
            engineerWindow.backWindow = this;
            this.setVisible(false);
        }
        
        //QUERY TIME! If username is in database, login successful!
        //If username doesn't exist, show popup "Invalid username/password"
        else {
        try{
                con = DriverManager.getConnection(DB_URL,USER,PASS);
                st = con.createStatement();
                String s = "select testerID from Tester;";
                rs = st.executeQuery(s);
                while (rs.next()) {
                    if (rs.getString(1).equals(username)) {
                        userFlag = true;
                        if(testerWindow == null) {
                            testerWindow = new TesterUI();
                        } 
//                        testerNAME = username;
//                        testerWindow.autotectiveLabel2.setText(username);
                        testerWindow.setVisible(true);
                        testerWindow.backWindow=this;
                        this.setVisible(false);
                    }   
            }
        }catch(SQLException e) {  
            }
        }
        
        //IF NONE OF THE ABOVE WORK, THEN PRODUCE ERROR MESSAGE
        if (userFlag != true)
            JOptionPane.showMessageDialog(null, "Invalid username/password");
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autotectiveLabel;
    private javax.swing.JRadioButton engineerButton;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    public javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
